### ISSUE TITLE
Can't run 

### ISSUE THREAD

**Issue by pizzalbj** [Fly-6/vue-vue-router-addRoutes#1]
你好，我是Link，是一名前端初学者。
    关注你再CSDN的vue路由动态加载的博客很久了，今天也在GitHub上发现了你的仓库。但是我download下来之后发现运行不了噢，一共报了两个错：一个是lazy.js里面的，一个是 ...mapGetters -- "Unexpected token"。
    如果可以的话，请尽快修复噢~

**Comment by quentin-wei** [comment]
楼上的朋友，问题你解决了吗？怎么解决的？
